export const CONTROL_PERMISSIONS = [
  'orders:read',
  'orders:manage',
  'orders:manage_tags',
  'purchasing:drafts:manage',
  'purchasing:closed:manage',
  'purchasing_from_po:drafts:manage',
  'direct_purchasing:drafts:manage',
  'dashboard:inventory',
  'inventory_count:drafts:manage',
  'inventory_count:closed:manage',
  'inventory_items:read',
  'inventory_items:manage',
  'menu:read',
  'menu:manage',
  'customers:read',
  'customers:read_insights',
  'customers:manage',
  'customers:manage_house_account',
  'customers:manage_loyalty',
  'suppliers:read',
  'suppliers:manage',
  'settings:manage_payment_methods',
  'users:manage',
  'branches:manage',
  'settings:manage',
  'settings:manage_taxes_and_groups',
  'settings:manage_charges',
  'settings:manage_tags',
  'settings:manage_reasons',
  'settings:manage_kitchen_flows',
  'settings:manage_reservations',
  'settings:manage_online_ordering',
  'settings:manage_price_tags',
  'settings:manage_notifications',
  'po:drafts:manage',
  'po:posted:manage',
  'po:approved:manage',
  'po:approved:receive',
  'reports:other',
  'reports:inventory_control',
  'reports:inventory_levels',
  'reports:inventory_transactions',
  'reports:sales',
  'reports:cost_adjustment_history',
  'delivery-partners:read',
  'delivery-partners:read_insights',
  'delivery-partners:manage',
  'delivery-partners:manage_house_account',
  'delivery-partners:manage_loyalty',
  'to:drafts:manage',
  'to:approved:manage',
  'transfers:drafts:manage',
  'transfers:closed:manage',
  'transfers:recieved:manage',
  'production:drafts:manage',
  'production:closed:manage',
  'quantity_adjustment:drafts:manage',
  'quantity_adjustment:closed:manage',
  'cost_adjustment:drafts:manage',
  'cost_adjustment:closed:manage',
  'order_transactions:read',
  'spot_check:drafts:manage',
  'spot_check:closed:manage',
  'count_sheet:drafts:manage',
  'ingredients:manage',
  'cost:manage',
  'coupons:manage',
  'devices:manage',
  'discounts:manage',
  'gift_cards:manage',
  'promotions:manage',
  'delivery_zones:manage',
  'timed_events:manage',
  'apps:manage',
  'dashboard:general',
  'dashboard:branches',
  'dashboard:call_center',
  'marketplace:manage',
  'cashier:access_cash_register',
  'cashier:access_device_management',
  'cashier:access_reports',
  'cashier:act_as_driver',
  'cashier:act_as_waiter',
  'cashier:add_open_charge',
  'cashier:add_open_price_product',
  'cashier:ahead_orders',
  'cashier:apply_discount',
  'cashier:apply_open_discount',
  'cashier:edit_products_sent_to_kitchen',
  'cashier:join_order',
  'cashier:open_cash_drawer',
  'cashier:perform_end_of_day',
  'cashier:print_check',
  'cashier:print_receipt',
  'cashier:return_order',
  'cashier:split_order',
  'cashier:view_done_orders',
  'cashier:void',
  'cashier:perform_payment',
  'cashier:edit_other_users_orders',
  'cashier:change_table_owner',
  'cashier:enroll_fingerprints',
  'cashier:send_to_kitchen_before_payment',
  'cashier:kitchen_reprint',
  'cashier:edit_tables_layout',
  'cashier:close_till_shift_with_active_orders',
  'cashier:manage_product_availability',
  'cashier:perform_spot_check',
  'cashier:pay_without_close',
  'cashier:manage_account_setup',
  // 'franchise:read',
  // 'franchise:manage',
  // 'sales_orders:read',
  // 'sales_orders:manage',
  // 'announcements:read',
  // 'announcements:manage',
  // 'requests_from_franchise:read',
  // 'requests_from_franchise:manage',
];

export const ZOOD_LIGHT_PERMISSIONS = [
  'orders:read',
  'orders:manage',
  'orders:manage_tags',

  'dashboard:inventory',
  'inventory_count:drafts:manage',
  'inventory_count:closed:manage',
  'inventory_items:read',
  'inventory_items:manage',

  'menu:read',
  'menu:manage',

  'customers:read',
  'customers:read_insights',
  'customers:manage',
  'customers:manage_house_account',
  'customers:manage_loyalty',

  'po:drafts:manage',
  'po:posted:manage',
  'po:approved:manage',
  'po:approved:receive',

  'purchasing:drafts:manage',
  'purchasing:closed:manage',
  'purchasing_from_po:drafts:manage',
  'direct_purchasing:drafts:manage',

  'suppliers:read',
  'suppliers:manage',

  'reports:other',
  'reports:inventory_control',
  'reports:inventory_levels',
  'reports:inventory_transactions',
  'reports:sales',
  'reports:cost_adjustment_history',

  'settings:manage_payment_methods',

  'users:manage',

  'branches:manage',

  'settings:manage',
  'settings:manage_taxes_and_groups',
  'settings:manage_charges',
  'settings:manage_tags',
  'settings:manage_reasons',
  'settings:manage_kitchen_flows',
  'settings:manage_reservations',
  'settings:manage_online_ordering',
  'settings:manage_price_tags',
  'settings:manage_notifications',
];

export const ZOOD_LIGHT_PERMISSIONS_GROUPS = {
  dashboard: {
    name: 'Dashboard',
    permissions: ['dashboard:inventory'],
  },

  invoices: {
    name: 'Invoices',
    permissions: [
      'orders:read',
      'orders:manage',
      'orders:manage_tags',
      'inventory_count:drafts:manage',
      'inventory_count:closed:manage',
      'inventory_items:read',
      'inventory_items:manage',
      'menu:read',
      'customers:read',
      'customers:read_insights',
      'customers:manage_house_account',
      'customers:manage_loyalty',
    ],
  },

  priceQuotes: {
    name: 'Price Quotes',
    permissions: [
      'po:drafts:manage',
      'po:posted:manage',
      'po:approved:manage',
      'po:approved:receive',
      'inventory_count:drafts:manage',
      'inventory_count:closed:manage',
      'inventory_items:read',
      'inventory_items:manage',
      'menu:read',
      'customers:read',
      'customers:read_insights',
      'customers:manage_house_account',
      'customers:manage_loyalty',
    ],
  },

  purchasing: {
    name: 'Purchasing',
    permissions: [
      'purchasing:drafts:manage',
      'purchasing:closed:manage',
      'purchasing_from_po:drafts:manage',
      'direct_purchasing:drafts:manage',
      'suppliers:read',
      'inventory_count:drafts:manage',
      'inventory_count:closed:manage',
      'inventory_items:read',
      'inventory_items:manage',
      'menu:read',
    ],
  },

  inventory: {
    name: 'Inventory',
    permissions: [
      'inventory_count:drafts:manage',
      'inventory_count:closed:manage',
      'inventory_items:read',
      'inventory_items:manage',
      'menu:read',
      'menu:manage',
    ],
  },

  customers: {
    name: 'Customers',
    permissions: [
      'customers:read',
      'customers:read_insights',
      'customers:manage',
      'customers:manage_house_account',
      'customers:manage_loyalty',
    ],
  },

  suppliers: {
    name: 'Suppliers',
    permissions: ['suppliers:read', 'suppliers:manage'],
  },

  reports: {
    name: 'Reports',
    permissions: [
      'reports:other',
      'reports:inventory_control',
      'reports:inventory_levels',
      'reports:inventory_transactions',
      'reports:sales',
      'reports:cost_adjustment_history',
      'purchasing:drafts:manage',
      'purchasing:closed:manage',
      'purchasing_from_po:drafts:manage',
      'direct_purchasing:drafts:manage',
    ],
  },

  paymentMethods: {
    name: 'Payment Methods',
    permissions: ['settings:manage_payment_methods'],
  },

  users: {
    name: 'Users & Permissions',
    permissions: ['users:manage'],
  },

  branches: {
    name: 'Branches',
    permissions: ['branches:manage'],
  },

  settings: {
    name: 'Settings',
    permissions: [
      'settings:manage',
      'settings:manage_taxes_and_groups',
      'settings:manage_charges',
      'settings:manage_tags',
      'settings:manage_reasons',
      'settings:manage_kitchen_flows',
      'settings:manage_reservations',
      'settings:manage_online_ordering',
      'settings:manage_price_tags',
      'settings:manage_notifications',
    ],
  },
};

export const CONTROL_PERMISSIONS_GROUPS = {
  order: {
    name: 'Order Authorities',
    permissions: [
      { label: 'Read Orders', value: 'orders:read' },
      { label: 'Manage Orders', value: 'orders:manage' },
      { label: 'Manage Orders Tags', value: 'orders:manage_tags' },
    ],
  },

  customer: {
    name: 'Customer Authorities',
    permissions: [
      { label: 'Read Customers', value: 'customers:read' },
      { label: 'Read Customers Insights', value: 'customers:read_insights' },
      { label: 'Manage Customers', value: 'customers:manage' },
      {
        label: 'Manage Customers House Account',
        value: 'customers:manage_house_account',
      },
      { label: 'Manage Customers Loyalty', value: 'customers:manage_loyalty' },
    ],
  },

  deliveryPartners: {
    name: 'Delivery Partners Authorities',
    permissions: [
      { label: 'Read Delivery Partners', value: 'delivery-partners:read' },
      {
        label: 'Read Delivery Partners Insights',
        value: 'delivery-partners:read_insights',
      },
      { label: 'Manage Delivery Partners', value: 'delivery-partners:manage' },
      {
        label: 'Manage Delivery Partners House Account',
        value: 'delivery-partners:manage_house_account',
      },
      {
        label: 'Manage Delivery Partners Loyalty',
        value: 'delivery-partners:manage_loyalty',
      },
    ],
  },

  // franchising: {
  //   name: 'Franchising Authorities',
  //   permissions: [
  //     { label: 'Read Franchise', value: 'franchise:read' },
  //     { label: 'Manage Franchise', value: 'franchise:manage' },
  //     { label: 'Read Sales Orders', value: 'sales_orders:read' },
  //     { label: 'Manage Sales Orders', value: 'sales_orders:manage' },
  //     { label: 'Read Announcements', value: 'announcements:read' },
  //     { label: 'Manage Announcements', value: 'announcements:manage' },
  //     {
  //       label: 'Read Requests From Franchise',
  //       value: 'requests_from_franchise:read',
  //     },
  //     {
  //       label: 'Manage Requests From Franchise',
  //       value: 'requests_from_franchise:manage',
  //     },
  //   ],
  // },

  inventory: {
    name: 'Inventory Authorities',
    permissions: [
      { label: 'Read Inventory Items', value: 'inventory_items:read' },
      { label: 'Manage Inventory Items', value: 'inventory_items:manage' },
      { label: 'Read Suppliers', value: 'suppliers:read' },
      { label: 'Manage Suppliers', value: 'suppliers:manage' },
      { label: 'Create Purchase Orders', value: 'po:drafts:manage' },
      { label: 'Submit Purchase Orders', value: 'po:posted:manage' },
      { label: 'Approve Purchase Orders', value: 'po:approved:manage' },
      { label: 'View Approved Purchase Orders', value: 'po:approved:receive' },
      { label: 'Create Transfer Orders', value: 'to:drafts:manage' },
      { label: 'Submit Transfer Orders', value: 'to:approved:manage' },
      { label: 'Create Transfers', value: 'transfers:drafts:manage' },
      { label: 'Send Transfers', value: 'transfers:closed:manage' },
      { label: 'Receive Transfers', value: 'transfers:recieved:manage' },
      { label: 'Create Purchasing', value: 'purchasing:drafts:manage' },
      { label: 'Submit Purchasing', value: 'purchasing:closed:manage' },
      {
        label: 'Create Purchasing From PO',
        value: 'purchasing_from_po:drafts:manage',
      },
      {
        label: 'Create Direct Purchasing',
        value: 'direct_purchasing:drafts:manage',
      },
      { label: 'Create Production', value: 'production:drafts:manage' },
      { label: 'Submit Production', value: 'production:closed:manage' },
      {
        label: 'Create Quantity Adjustment',
        value: 'quantity_adjustment:drafts:manage',
      },
      {
        label: 'Submit Quantity Adjustment',
        value: 'quantity_adjustment:closed:manage',
      },
      {
        label: 'Create Cost Adjustment',
        value: 'cost_adjustment:drafts:manage',
      },
      {
        label: 'Submit Cost Adjustment',
        value: 'cost_adjustment:closed:manage',
      },
      {
        label: 'Create Inventory Count',
        value: 'inventory_count:drafts:manage',
      },
      {
        label: 'Submit Inventory Count',
        value: 'inventory_count:closed:manage',
      },
      { label: 'Read Order Transactions', value: 'order_transactions:read' },
      {
        label: 'Create Inventory Spot Check',
        value: 'spot_check:drafts:manage',
      },
      {
        label: 'Submit Inventory Spot Check',
        value: 'spot_check:closed:manage',
      },
      {
        label: 'Read Inventory Count Sheet',
        value: 'count_sheet:drafts:manage',
      },
    ],
  },

  menu: {
    name: 'Menu Authorities',
    permissions: [
      { label: 'Read Menu', value: 'menu:read' },
      { label: 'Manage Menu', value: 'menu:manage' },
    ],
  },

  other: {
    name: 'Other Authorities',
    permissions: [
      { label: 'Manage Ingredients', value: 'ingredients:manage' },
      { label: 'Manage Costs', value: 'cost:manage' },
    ],
  },

  admin: {
    name: 'Admin Authorities',
    permissions: [
      { label: 'Manage Branches', value: 'branches:manage' },
      { label: 'Manage Coupons', value: 'coupons:manage' },
      { label: 'Manage Devices', value: 'devices:manage' },
      { label: 'Manage Discounts', value: 'discounts:manage' },
      { label: 'Manage Gift Cards', value: 'gift_cards:manage' },
      { label: 'Manage Promotions', value: 'promotions:manage' },
      { label: 'Manage Settings', value: 'settings:manage' },
      { label: 'Manage Delivery Zones', value: 'delivery_zones:manage' },
      { label: 'Manage Timed Events', value: 'timed_events:manage' },
      { label: 'Manage Users', value: 'users:manage' },
      { label: 'Manage Apps', value: 'apps:manage' },
      {
        label: 'Manage Taxes & Tax Groups',
        value: 'settings:manage_taxes_and_groups',
      },
      { label: 'Payment Methods', value: 'settings:manage_payment_methods' },
      { label: 'Manage Charges', value: 'settings:manage_charges' },
      { label: 'Manage Tags', value: 'settings:manage_tags' },
      { label: 'Manage Reasons', value: 'settings:manage_reasons' },
      { label: 'Manage Kitchen Flows', value: 'settings:manage_kitchen_flows' },
      { label: 'Manage Reservations', value: 'settings:manage_reservations' },
      {
        label: 'Manage Online Ordering',
        value: 'settings:manage_online_ordering',
      },
      { label: 'Manage Price Tags', value: 'settings:manage_price_tags' },
      { label: 'Manage Notifications', value: 'settings:manage_notifications' },
    ],
  },

  reports: {
    name: 'Reports Authorities',
    permissions: [
      {
        label: 'View Inventory Control Report',
        value: 'reports:inventory_control',
      },
      {
        label: 'View Inventory Levels Report',
        value: 'reports:inventory_levels',
      },
      {
        label: 'Inventory Transactions Reports',
        value: 'reports:inventory_transactions',
      },
      { label: 'View Other Reports', value: 'reports:other' },
      { label: 'View Sales Reports', value: 'reports:sales' },
      {
        label: 'View Cost Adjustment History Report',
        value: 'reports:cost_adjustment_history',
      },
    ],
  },

  dashboard: {
    name: 'Dashboard Authorities',
    permissions: [
      { label: 'Access General Dashboard', value: 'dashboard:general' },
      { label: 'Access Branches Dashboard', value: 'dashboard:branches' },
      { label: 'Access Inventory Dashboard', value: 'dashboard:inventory' },
      { label: 'Access Call Center Dashboard', value: 'dashboard:call_center' },
    ],
  },

  marketplace: {
    name: 'Marketplace Authorities',
    permissions: [{ label: 'Manage Marketplace', value: 'marketplace:manage' }],
  },

  cashierApp: {
    name: 'Cashier App Authorities',
    permissions: [
      { label: 'Access Cash Register', value: 'cashier:access_cash_register' },
      {
        label: 'Access Devices Management',
        value: 'cashier:access_device_management',
      },
      { label: 'Access Reports', value: 'cashier:access_reports' },
      { label: 'Act as Driver', value: 'cashier:act_as_driver' },
      { label: 'Act as Waiter', value: 'cashier:act_as_waiter' },
      { label: 'Add Open Charge', value: 'cashier:add_open_charge' },
      {
        label: 'Add Open Price Product',
        value: 'cashier:add_open_price_product',
      },
      { label: 'Apply Ahead Orders', value: 'cashier:ahead_orders' },
      { label: 'Apply Predefined Discounts', value: 'cashier:apply_discount' },
      { label: 'Apply Open Discounts', value: 'cashier:apply_open_discount' },
      {
        label: 'Edit Products Sent to Kitchen',
        value: 'cashier:edit_products_sent_to_kitchen',
      },
      { label: 'Join Order', value: 'cashier:join_order' },
      { label: 'Access Drawer Operations', value: 'cashier:open_cash_drawer' },
      { label: 'Perform End of Day', value: 'cashier:perform_end_of_day' },
      { label: 'Print Check', value: 'cashier:print_check' },
      { label: 'Print Receipt', value: 'cashier:print_receipt' },
      { label: 'Return Order', value: 'cashier:return_order' },
      { label: 'Split Order', value: 'cashier:split_order' },
      { label: 'View Done Orders', value: 'cashier:view_done_orders' },
      { label: 'Void Orders and Products', value: 'cashier:void' },
      { label: 'Perform Payment', value: 'cashier:perform_payment' },
      {
        label: 'Edit Orders Opened by Other Users',
        value: 'cashier:edit_other_users_orders',
      },
      { label: 'Change Table Owner', value: 'cashier:change_table_owner' },
      {
        label: 'Register Users Fingerprint',
        value: 'cashier:enroll_fingerprints',
      },
      {
        label: 'Send to Kitchen Before Payment',
        value: 'cashier:send_to_kitchen_before_payment',
      },
      { label: 'Kitchen Reprint', value: 'cashier:kitchen_reprint' },
      { label: 'Edit Tables Layout', value: 'cashier:edit_tables_layout' },
      {
        label: 'Close Till/Shift With Active Orders',
        value: 'cashier:close_till_shift_with_active_orders',
      },
      {
        label: 'Manage Product Availability',
        value: 'cashier:manage_product_availability',
      },
      { label: 'Perform Spot Check', value: 'cashier:perform_spot_check' },
      {
        label: 'Pay Orders Without Closing',
        value: 'cashier:pay_without_close',
      },
      { label: 'Account Setup', value: 'cashier:manage_account_setup' },
    ],
  },
};
