import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Sidbar from '@/components/layout/Sidbar';
import NavBar from '@/components/layout/NavBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Subscriptions',
  description: 'Generated by (Moemen & Abdelrahman)',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidbar />
        <NavBar />
        <main className='pt-16 md:ml-64 transition-all duration-300 ease-in-out'>
          <div className='p-6 bg-[#FAFAFA] min-h-[calc(100vh-64px)]'>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
